package main

import (
	"bytes"
	"encoding/json"
	"flag"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"text/template"
)

type catalogEntry struct {
	GoName string `json:"goName"`
	TSName string `json:"tsName"`
	Value  string `json:"value"`
}

type catalog struct {
	ProtocolVersion int            `json:"protocolVersion"`
	BridgeEventName string         `json:"bridgeEventName"`
	Kinds           []catalogEntry `json:"kinds"`
	Methods         []catalogEntry `json:"methods"`
	Events          []catalogEntry `json:"events"`
	Errors          []catalogEntry `json:"errors"`
}

var (
	checkOnly = flag.Bool("check", false, "verify generated files are current")
)

func main() {
	flag.Parse()

	root, err := os.Getwd()
	must(err)

	specPath := filepath.Join(root, "contracts", "bridge", "v1", "catalog.json")
	data, err := os.ReadFile(specPath)
	must(err)

	var spec catalog
	must(json.Unmarshal(data, &spec))

	goOutput := renderGo(spec)
	tsOutput := renderTS(spec)

	goPath := filepath.Join(root, "internal", "core", "bridge", "generated", "protocol_gen.go")
	tsPath := filepath.Join(root, "ui", "src", "bridge", "generated", "protocol.ts")

	if *checkOnly {
		ensureMatches(goPath, goOutput)
		ensureMatches(tsPath, tsOutput)
		return
	}

	writeFile(goPath, goOutput)
	writeFile(tsPath, tsOutput)
}

func renderGo(spec catalog) []byte {
	const tmpl = `// Code generated by scripts/generate_bridge_contract; DO NOT EDIT.

package generated

const (
	ProtocolVersion = {{ .ProtocolVersion }}
	BridgeEventName = "{{ .BridgeEventName }}"
{{- range .Kinds }}
	{{ .GoName }} = "{{ .Value }}"
{{- end }}
{{- range .Methods }}
	{{ .GoName }} = "{{ .Value }}"
{{- end }}
{{- range .Events }}
	{{ .GoName }} = "{{ .Value }}"
{{- end }}
{{- range .Errors }}
	{{ .GoName }} = "{{ .Value }}"
{{- end }}
)
`
	var buf bytes.Buffer
	must(template.Must(template.New("go").Parse(tmpl)).Execute(&buf, spec))
	formatted, err := format.Source(buf.Bytes())
	must(err)
	return formatted
}

func renderTS(spec catalog) []byte {
	const tmpl = `// Code generated by scripts/generate_bridge_contract; DO NOT EDIT.

export const PROTOCOL_VERSION = {{ .ProtocolVersion }} as const;
export const BRIDGE_EVENT_NAME = "{{ .BridgeEventName }}" as const;

export const KINDS = {
{{- range .Kinds }}
  {{ .TSName }}: "{{ .Value }}",
{{- end }}
} as const;
export type BridgeKind = (typeof KINDS)[keyof typeof KINDS];

export const METHODS = {
{{- range .Methods }}
  {{ .TSName }}: "{{ .Value }}",
{{- end }}
} as const;
export type BridgeMethod = (typeof METHODS)[keyof typeof METHODS];

export const EVENTS = {
{{- range .Events }}
  {{ .TSName }}: "{{ .Value }}",
{{- end }}
} as const;
export type BridgeEventName = (typeof EVENTS)[keyof typeof EVENTS];

export const ERROR_CODES = {
{{- range .Errors }}
  {{ .TSName }}: "{{ .Value }}",
{{- end }}
} as const;
export type BridgeErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];

export type BridgeError = {
  code: BridgeErrorCode;
  message: string;
  details: Record<string, unknown>;
  retriable: boolean;
};

export type BridgeRequestEnvelope<TParams extends Record<string, unknown>> = {
  v: typeof PROTOCOL_VERSION;
  kind: typeof KINDS.request;
  id: string;
  method: BridgeMethod;
  params: TParams;
};

export type BridgeResponseEnvelope<TResult> = {
  v: typeof PROTOCOL_VERSION;
  kind: typeof KINDS.response;
  id: string;
  ok: boolean;
  result?: TResult;
  error?: BridgeError;
};

export type BridgeEventEnvelope<TPayload> = {
  v: typeof PROTOCOL_VERSION;
  kind: typeof KINDS.event;
  event: BridgeEventName;
  payload: TPayload;
};
`
	var buf bytes.Buffer
	must(template.Must(template.New("ts").Parse(tmpl)).Execute(&buf, spec))
	return buf.Bytes()
}

func ensureMatches(path string, expected []byte) {
	actual, err := os.ReadFile(path)
	must(err)
	if !bytes.Equal(actual, expected) {
		fmt.Fprintf(os.Stderr, "generated file is stale: %s\n", path)
		os.Exit(1)
	}
}

func writeFile(path string, data []byte) {
	must(os.MkdirAll(filepath.Dir(path), 0755))
	must(os.WriteFile(path, data, 0644))
}

func must(err error) {
	if err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}
